In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv (r'/Users/Colin/Desktop/Research project/Sigma/Data - Final/Final Data.csv')
df

,gvkey,datadate,fyearq,fqtr,indfmt,consol,popsrc,datafmt,tic,cusip,...,txpq,uaptq,chechy,cogsy,dpy,niy,revty,xopry,xsgay,costat
0,1000,31/03/1970,1970,1.0,INDL,C,D,STD,AE.2,000032102,...,NaN,NaN,NaN,NaN,NaN,0.605,9.478,NaN,NaN,I
1,1000,30/06/1970,1970,2.0,INDL,C,D,STD,AE.2,000032102,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I
2,1000,30/09/1970,1970,3.0,INDL,C,D,STD,AE.2,000032102,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I
3,1000,31/12/1970,1970,4.0,INDL,C,D,STD,AE.2,000032102,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I
4,1000,31/03/1971,1971,1.0,INDL,C,D,STD,AE.2,000032102,...,NaN,NaN,NaN,NaN,NaN,0.346,7.983,NaN,NaN,I
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
627381,311524,30/09/2013,2013,3.0,INDL,C,D,STD,TAM,87509U106,...,4.0,NaN,-22.0,665.0,85.0,1.000,917.000,720.0,55.0,I
627382,311524,31/12/2013,2013,4.0,INDL,C,D,STD,TAM,87509U106,...,1.0,NaN,21.0,871.2,114.8,-7.000,1200.000,950.2,79.0,I
627383,311524,31/03/2014,2014,1.0,INDL,C,D,STD,TAM,87509U106,...,8.0,NaN,-54.0,232.0,32.0,10.000,319.000,249.0,17.0,I
627384,311524,30/06/2014,2014,2.0,INDL,C,D,STD,TAM,87509U106,...,4.0,NaN,-21.0,503.0,66.0,24.000,689.000,542.0,39.0,I
627385,311524,30/09/2014,2014,3.0,INDL,C,D,STD,TAM,87509U106,...,4.0,NaN,-3.0,775.0,101.0,53.000,1058.000,836.0,61.0,I

In [5]:
len(df.columns)

32